### ISSUE TITLE
Running Exercise 3.6.6  lower right plot

### ISSUE THREAD

**Issue by williamzoughaib** [gabd-students/zoughaib_william#3]
I am having issues matching my plot to the pictured plot in the book.  I used shape=21, stroke=2, and size=3.  

```{r}
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy,color=drv),shape=21,stroke=2,size=3)
```
This is what code chunk I ran.  I would appreciate some help with this.  I did the other 5 graphs without any issues.

**Comment by mtaylor-semo** [comment]
Answered in the public forum.
